- src/azure_hl.rs
> Fix the build

- src/azure_hl.rs
> Replaced int/uint with isize/usize.

- src/azure.rs
- src/azure_hl.rs
Remove the second color type and move the auxiliar function to servo's color.rs.
> Remove the second color type

- src/azure-c.cpp
- src/azure-c.h
- src/azure.rs
- src/azure_hl.rs
Depends on #130 (because of the Pattern part)
> Added RadialGradient support

- src/azure-c.cpp
- src/azure-c.h
- src/azure.rs
- src/azure_hl.rs
You can now use `quadraticCurveTo()`.
> Added quadratic bezier curve support.

- src/azure-c.cpp
- src/azure-c.h
Someone left some tabs in the indentation.
> Fix mixed space/tab indentation

- src/linkhack.rs
r? anybody
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/155)
> Roll back stlport change until it can be done across the whole codebase

- Cargo.toml
- makefile.cargo
Part of servo/servo#6088. Depends on servo/skia#47. r? @SimonSapin
> Use Cargo metadata to find include dirs

- Cargo.toml
- src/azure_hl.rs
> Fix dependencies.

- Cargo.toml
- makefile.cargo
Please consider merging this changes as they were required to get servo compiling on raspberry pi2.
> Porting to raspberry pi2.

- makefile.cargo
> Add ARM cross-compile support.

- src/azure-c.cpp
- src/azure-c.h
- src/azure.rs
- src/azure_hl.rs
Required to get tiling working right.
r? @glennw
> Allow the matrix to be supplied for surface patterns.

- Cargo.toml
- src/azure.rs
- src/azure_hl.rs
- src/lib.rs
This is preparation for multiprocess Servo.
r? @metajack
> Make colors and gradient stops serializable using `serde`.

- build.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/190)
> Use NUM_JOBS to control make -j

- src/azure_hl.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/191)
> Allow calling stroke_line with PatternRef

- Cargo.toml
- src/azure.rs
- src/azure_hl.rs
- src/lib.rs
Part of servo/heapsize#5.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/193)
> Add heapsize support.

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/194)
> Use crates.io heapsize.

- src/azure.rs
AzAntialiasMode = enum_AzCompositionOp => AzAntialiasMode = enum_AzAntialiasMode
r? @mbrubeck
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/198)
> Fix AzAntialiasMode typo

- Cargo.toml
- src/azure.rs
- src/azure_hl.rs
- src/lib.rs
Depends on https://github.com/servo/euclid/pull/111, https://github.com/servo/io-surface-rs/pull/41, https://github.com/servo/skia/pull/80
r? @jdm
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/204)
> Make serde optional, bump crates (breaking)

- Cargo.toml
- src/azure-c.cpp
- src/azure-c.h
- src/azure.rs
- src/azure_hl.rs
- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/208)
> Add Path::IsPointInPath and Path::CopyToPathBuilder

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/219)
> Allow serde 0.7

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/221)
> Specify package dependencies in 'addons' travis.yml section.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/224)
> Update dependencies in Cargo.toml to match src/lib.rs

- Cargo.toml
r? @mbrubeck
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/225)
> Update skia dependency

- .gitignore
- makefile.cargo
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/227)
> Enable ccache

- Cargo.toml
- src/azure_hl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/236)
> Updates required for using Euclid 0.8

- CMakeLists.txt
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/237)
> Fix freetype2 include dir, and dwrite build on windows

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/238)
> Bump to 0.6.1

- CMakeLists.txt
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/239)
> Always build ScaledFontDWrite for Windows

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/240)
> Update to serde 0.8

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/241)
> Fix OS X dependencies with regard to serde support

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/242)
> Update euclid to 0.10

- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/246)
> Switch rustc_macro to proc_macro

- src/azure_hl.rs
Extracted from servo's gfx_traits::color module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/247)
> Add some methods on the Color type.

- Cargo.toml
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/248)
> Use heapsize_derive

- Cargo.toml
- src/azure.rs
- src/azure_hl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/251)
> Remove various transmutes which were UB

- Cargo.toml
- src/azure-c.cpp
- src/azure.rs
- src/azure_hl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/252)
> Remove transmute calls.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/254)
> Update core-graphics to 0.5; bump minor version.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/255)
> Update servo-skia to 0.30000000

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/256)
> Update servo-skia to 0.30000001

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/257)
> Update euclid to 0.11

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/258)
> Update core-text to 4.0

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/259)
> Update skia to 0.30000003

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/261)
> Update skia and bump version number.

- Cargo.toml
Also bump version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/263)
> Bump euclid, heapsize and skia

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/265)
> Bump serde to 1.0 and bump version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/266)
> Add description and license to Cargo.toml

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/267)
> Update euclid and skia

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/268)
> Upgrade to core-text 6.0.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/269)
> Bump freetype dependency.

- Cargo.toml
- libazure/2D.h
- libazure/Path.cpp
- libazure/PathAnalysis.h
- libazure/PathCG.cpp
- libazure/PathCG.h
- libazure/PathCairo.cpp
- libazure/PathRecording.h
- libazure/PathSkia.cpp
- libazure/PathSkia.h
- patches/arc_update.patch
- src/azure-c.cpp
- src/azure-c.h
- src/azure.rs
- src/azure_hl.rs
Bug: https://github.com/servo/servo/issues/17598
The ellipse API was added as public API of Azure and the Arc method was updated to deal with the ellipse API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/272)
> Implement Ellipse API

- Cargo.toml
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/275)
> Bump mac deps

- Cargo.toml
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/276)
> Remove more unused dependencies

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/277)
> Bump versions.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/280)
> Update servo-skia to 0.30000008

- Cargo.toml
Depends on https://github.com/servo/skia/pull/149
This will be necessary for https://github.com/servo/servo/pull/19895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/283)
> skia update

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/285)
> Update euclid to 0.17 and bump version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/286)
> Update servo-skia to 0.30000014

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/287)
> Update skia and bump version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/289)
> Update euclid and bump version

- Cargo.toml
- src/azure-c.cpp
- src/azure.rs
- src/azure_hl.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/288)
> Add API for transforming a path into a path builder.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/290)
> Update skia to 0.30000017.0

- src/azure-c.cpp
SkTypes.h is described in Skia as "the root of the public header files", and includes a series of headers that define various configuration flags that the rest of skia relies upon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/292)
> Ensure skia configuration is correct in C bindings.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/298)
> Bump servo-skia version

- CMakeLists.txt
- Cargo.toml
Same reasoning as servo/skia#176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/299)
> build: Don't auto opt-in to ccache.

- .travis.yml
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/303)
> Fix TravisCI and Appveyor builds.

- src/azure-c.cpp
- src/azure.rs
- src/azure_hl.rs
- src/lib.rs
This is needed to fix the azure backend in servo with the raqote
changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/302)
> Implement Clone for azure_hl::Path

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/304)
> Update skia. Publish 0.37.0.
