servo/rust-azure

Cargo.toml, src/azure_hl.rs, src/lib.rs
This is to allow rust-layers to depend on azure and avoid a circular
dependency. rust-layers will soon be handling more of the glue that
attaches shared surfaces to Servo.
=> Remove the dependency on rust-layers

makefile.cargo
Assuming that any target that doesn't have "arm" in its name is i686 or x86_64
and thus SSE2-compatible is incorrect (counter example: aarch64). It's better to
look for "86", which appears in the name of all 8086 descendants.
=> Enhance the detection of SSE2-compatible targets

src/azure_hl.rs
After that PR the build fails with:
mismatched types: expected `usize`, found `isize` (expected usize, found isize)
=> Fix build after PR #137

src/azure.rs, src/azure_hl.rs
This should easy the use of AzColor by servo (e.g. layout_task.rs).
=> Implementing equality operator for AzColor and Color objects.

src/azure.rs, src/azure_hl.rs
In Moz2D StrokeOptions (and pretty much all structures) are meant to be immutable. This also hides some ugly pointer unboxing in rust-azure. Submitting a separate patch for servo.
=> StrokeOptions is meant to be immutable and add JoinStyle and CapStyle.

src/azure_hl.rs
Somehow I missed this little bug when I uploaded the radial gradient patch, but here's the fix.
=> Fixed crash on empty gradient stops vector.

src/azure-c.cpp, src/azure-c.h, src/azure.rs, src/azure_hl.rs
The arcTo funtion of the canvas requires to know the last point of the current path for calculations. Is it ok to get it like this?
=> Added a way to get the current point of the path.

src/azure-c.h, src/azure.rs, src/azure_hl.rs
This patch fixes the handling of line cap and line join. According to 2D.h, both of these are 1-byte values, and not bitfields.
This is the azure-side patch of servo/servo#5635.
=> Fix line cap and line join.

src/azure_hl.rs
Added Clone trait for some structs, now we can save/restore the canvas context state.
Required by servo/servo#5731.
=> Add Clone trait for some structs.

src/linkhack.rs
stlport is the right library to use and allows us to link properly on Gonk.
=> Use stlport rather than stdc++ on Android

src/azure-c.cpp, src/azure-c.h, src/azure.rs, src/azure_hl.rs
I'm interested in implementing canvas features for servo.
SurfacePattern seems to be needed to support pattern fill for canvas.
=> Add support for surface pattern.

src/azure-c.h, src/azure.rs, src/azure_hl.rs
This patch fixes the implementation of the composition and antialias fields in DrawOptions, and allows to properly set antialiasing. Also adds a default constructor for DrawOptions.
=> Fix antialias in DrawOptions

src/azure-c.cpp, src/azure-c.h, src/azure.rs, src/azure_hl.rs
SurfacePattern has ExtendMode::REPEAT.
Clipping is used to handle 'repeat-x', 'repeat-y' and 'no-repeat'.
=> Implement fill_rect for surface pattern with repetition style.

src/azure-c.cpp, src/azure-c.h, src/azure.rs, src/azure_hl.rs
- Modify fill and stroke functions to handle all pattern types.
- Add the code to check the zero size gradient.
- Set ExtendMode::Clamp for SurfacePattern in case of no-repeat.
r? @pcwalton @nox @jdm 
cc @yichoi
=> Patches for fill and stroke on canvas in servo.

makefile.cargo
This reverts commit 1e7317e66a3f4e9b256d6e9190038b222fc8e603.
This commit has caused some issues with Android builds. This revert
rolls it out for the moment so that we can fix it later and have Android
building now.
=> Do not use system include path for freetype

src/azure-c.cpp, src/azure_hl.rs, src/linkhack.rs, src/scaled_font.rs, src/test.rs
r? @metajack 
I've tested this PR against OSX, OSX/cef, and Linux (OSX/cef is where we were seeing the issue in the rustup). The code being removed was causing us to pull in the static library twice and then rely on the linker to remove / deal with the second copy.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/181)
=> We do not need to link against skia because it is statically pulled in

.travis.yml, src/azure_hl.rs
GLContext has been split out from GLRasterizationContext.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/187)
=> Update to support the latest skia

.travis.yml, build.rs, makefile.cargo
This fixes cross compilation issues, so it now builds correctly for both Android and ARM.
(See servo/servo#6537)
Part of servo/servo#6327.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/189)
=> Fix cross compilation issues

src/azure_hl.rs
When a script defines a bigger area for a Canvas element than it was defined by CSS style, Servo will panic and exit execution.
This patch fix this bug.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/195)
=> This will fix a panic in Canvas

src/azure_hl.rs
Some Azure backends will return a null source surface if the size is
zero, which was causing a crash. This patch forces callers to handle
this case by returning an option.
r? @mbrubeck
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/201)
=> Make `create_source_surface_from_data` fallible.

makefile.cargo
The DEP_FREETYPE_OUTDIR variable is not available when using freetype2 via pkg-config.  (See servo/libfreetype2#17.)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/203)
=> Use pkg-config to find freetype include dir

build.rs, src/linkhack.rs
Using cargo linking directives fixes a bunch of link issues on Windows here, including being able to do a static link of the azure lib.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/205)
=> Stop doing linkhack linking, at least on Windows

Cargo.toml
Fix #206 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/207)
=> Use skia and deps from crates.io

src/azure.rs, src/azure_hl.rs, src/scaled_font.rs
Leaving out DrawTarget/DrawTargetBacking, as the latter includes
GLRasterizationContext from Skia, which is missing Debug.
(And I don't feel like doing this for Skia right now -- this is already
quite getting out of hand...)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/212)
=> Derive Debug for (almost) all public types

src/azure.rs
Attribute #[inline] can only be put on functions and #[repr(C)] on
structs and enums.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/217)
=> Bump to Rust nightly 2016-02-22

Cargo.toml
@mbrubeck I think this is what prevents us to move to the updated skia in servo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/226)
=> Bumping version to 0.4.5 to force other packages to pick up new skia

.travis.yml, CMakeLists.txt, Cargo.toml, src/lib.rs
We also bump to 0.5.0 as it should have been done when switching to CMake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/233)
=> Correctly ask support for C++11 to CMake

Cargo.toml, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/245)
=> Switch to serde_derive

Cargo.toml, src/azure_hl.rs
In order for this to build we need servo-skia to be published on crates.io.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/264)
=> Bump euclid to 0.14

Cargo.toml, libazure/Types.h
2 errors encountered when cross compiling for Android on macOS.
- freetype not found:
all(target_os = "linux", target_os = "android"), a falsy value, is used as condition to add freetype crate dep. Building on Linux doesn't fail because freetype is most likely installed there as the fallback.
- INT16_(MIN|MAX), referenced in libazure/SIMD.h, are not defined:
Although libazure/Types.h does define __STDC_LIMIT_MACROS before including stdint.h, it's too late because that header is also included in libazure/mozilla/NullPtr.h a few lines above.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/270)
=> Build for Android on macOS

libazure/PathD2D.cpp, libazure/PathD2D.h, patches/PathD2D_Arc.patch
Arc method was updated to support Ellipse API of Canvas 2D:
https://github.com/servo/rust-azure/commit/648e112bbf15a8b741553300a422381c2971b69e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/273)
=> Add aRadiusX and aRadiusY to Arc method in PathBuilderD2D

libazure/PathD2D.cpp, libazure/PathD2D.h, patches/aRotationAngle.patch
Arc method was updated to support Ellipse of Canvas 2D API:
https://github.com/servo/rust-azure/commit/648e112bbf15a8b741553300a422381c2971b69e
But, aRotationAngle parameter was missed in the following commit:
https://github.com/servo/rust-azure/commit/ddb3cf07b11c2047055148655aec1e2b8b4f0cbd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/274)
=> Add aRotationAngle to Arc method in PathBuilderD2D

Cargo.toml, src/azure.rs, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/281)
=> Cleanup dependencies

Cargo.toml
This is a PR in a series of PRs originating at https://github.com/servo/core-foundation-rs/pull/132
The plan is to make a breaking change to `core-foundation` and release it as `0.5.0`. Hopefully we can manage to bring Servo and its entire dependency tree up to date as rapidly as possible in combination with this, as to use only the new core-foundation in Servo and all its deps. :)
TODO before merge:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/282)
=> Upgrade core foundation

Cargo.toml, src/azure_hl.rs
We move SourceSurfaceMethods items to inherent methods on the couple of surface
types and we make DataSourceSurface::with_data into DataSourceSurface::data,
which is unsafe and returns a slice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-azure/293)
=> Clean up surface methods
